### ISSUE TITLE
Training should use the chat bot's preprocessors

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1006]
Currently, when a chat bot is trained, the dialog is saved directly to the database. This needs to be changed so that the training data can be cleaned and tagged by the chat bot's preprocessors.

***

Related to https://github.com/gunthercox/ChatterBot/issues/954#issuecomment-324920752

**Comment by isaam14** [comment]
@gunthercox  What can I do if I don't want the training to be done with preprocessors? (because the preprocessors I use convert uppercase and unicode to lowercase and ascci respectively, but I want the responses to have uppercase and unicode in some cases)
Is there a way to set the preprocessors after the training?
