### ISSUE TITLE
Get last response from bot

### ISSUE THREAD

**Issue by DaCodaHUB** [gunthercox/ChatterBot#1131]
How do I retrieve the last response from bot?
I was trying to use "storage.get_last_response" but I don't understand what to put in as arguments. I was trying it with the terminal_example.py
And what exactly is "conversation_id"? I don't understand the purpose of it.

**Comment by gunthercox** [comment]
The `get_latest_response` takes a single argument, a conversation id. The conversation id is a unique identifier that corresponds to a group of statements that make up a conversation. It is used so that the chat bot can track a conversation and know that it is responding to the latest statement in the conversation.
