### ISSUE TITLE
Context for tests

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#123]
When I am writing tests for logic adapters, I get errors relating to the self.context variable being NoneType. @gunthercox Any ideas how to implement context in tests?

**Comment by gunthercox** [comment]
The `self.context` variable is typically the current instance of the `ChatBot` class or a subclass of `Adaptation`. What tests are you trying to write tests for that you are seeing these errors on?

**Comment by DarkmatterVale** [comment]
I am writing tests for logic adapters I am creating, and I have to find a workaround because the code (which would work on all actual systems) breaks in testing. This is due to the context variable not being set for adapters in tests. An example of when this occurs is if I have "self.context.io.process(...)", it will throw an error because self.context is of NoneType.

**Comment by gunthercox** [comment]
> An example of when this occurs is if I have "self.context.io.process(...)", it will throw an error because self.context is of NoneType.

This makes sense, since nothing has been assigned to `self.context` then it is None. By default, the context also doesn't have any adapters added to it so there is nothing to call the `process()` method on.

You have two options for setting up tests.
1. Create a mock object and add the adapters you want to test with to it.
You may be able to do this by doing something like:
```python
context = Adaptation()
context.add_adapter(my_io_adapter)
context.add_adapter(my_storage_adapter)
...
```

2. Test at a higher level.
Create a test ChatBot() instance and specify only your adapter as a parameter.

**Comment by DarkmatterVale** [comment]
I see what you are saying. I am going to close this issue then, because this will solve my problem.
