### ISSUE TITLE
Regarding License Terms

### ISSUE THREAD

**Issue by srss-raju** [gunthercox/ChatterBot#1258]
Hi Team,

I would like to use ChatterBot in my application. Just want to know licensing terms when it get commercialise.
Do I need to Pay anything / do I need to display a logo etc..

Thanks and Regards
Rajesh

**Comment by vkosuri** [comment]
Read more about chatterbot license https://github.com/gunthercox/ChatterBot/blob/master/LICENSE

In short this is how it looks

![image](https://user-images.githubusercontent.com/13664257/37808441-5d8222a2-2e70-11e8-81b9-e4bd8a366578.png)

**Comment by srss-raju** [comment]
Thanks for reply.

Can you please explain the below statement in detail.

Neither the name of ChatterBot nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

endorse or promote 

how would you like use to do this ?
Any logo / name etc should we display or what ?

Thanks 
Rajesh

**Comment by vkosuri** [comment]
> Neither the name of ChatterBot nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Yes you need get approval from author @gunthercox either through email/written copy and get it back a singed copy.

**Comment by gunthercox** [comment]
Hi @srss-raju you don't need to pay anything or display a logo. ChatterBot is free to use commercially because it is licensed under a standard [BSD license](https://opensource.org/licenses/BSD-3-Clause). Many popular Python libraries also use this license such as [Django](https://github.com/django/django/blob/master/LICENSE), [Django REST Framework](https://github.com/encode/django-rest-framework/blob/master/LICENSE.md) and the [Python programming language](https://en.wikipedia.org/wiki/Python_Software_Foundation_License) itself.

**Comment by vkosuri** [comment]
Master, One question, If the person/organization is going to modify any algorithm/codebase does it required any approval?

**Comment by gunthercox** [comment]
No approval is needed for code modifications.

**Comment by vkosuri** [comment]
@srss-raju did you received all required information?
