### ISSUE TITLE
Training for specific answer

### ISSUE THREAD

**Issue by shirishph** [gunthercox/ChatterBot#1321]
I'm trying to train the bot with a specific answer to a specific question by training. See this code below...

``` Python
from chatterbot import ChatBot
import json
import sys
from pymongo import MongoClient
from chatterbot.trainers import Trainer
from chatterbot.conversation.response import Response
from pprint import pprint

class MyTrainer(Trainer):

  def __init__(self, storage, **kwargs):
    super(MyTrainer, self).__init__(storage, **kwargs)
    print('MyTrainer/Init')

  def train(self, *args, **kwargs):
    print('\ntraining...')
    
    actual_statement = 'power brick'
    desired_response1 = 'ensure the light is on'
    statement = self.get_or_create(actual_statement)
    response = Response(desired_response1)
    statement.add_response(response)
    self.storage.update(statement)

    print('statement: ')
    pprint(vars(statement))
    print('response: ')
    pprint(vars(response))
    print('found this: ')
    pprint(vars(self.storage.find('power brick')))

    print('done')

chatbot = ChatBot(
            'NewCup',
            show_training_progress=True,
            storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
            database='chatter')
chatbot.set_trainer(MyTrainer)
chatbot.train()

print('\n---\n')
```

After running this, the output is like so...

``` Bash
$ python3 question.py
MyTrainer/Init

training...
statement:
{'confidence': 0,
 'extra_data': {},
 'in_response_to': [<Response text:ensure the light is on>,
                    <Response text:How do you drive an intergalactic spaceship>],
 'storage': None,
 'tags': [],
 'text': 'power brick'}
response:
{'created_at': datetime.datetime(2018, 6, 12, 8, 55, 0, 168230),
 'occurrence': 1,
 'text': 'ensure the light is on'}
found this:
{'confidence': 0,
 'extra_data': {},
 'in_response_to': [<Response text:ensure the light is on>,
                    <Response text:How do you drive an intergalactic spaceship>],
 'storage': None,
 'tags': [],
 'text': 'power brick'}
done

---
```
note: The 'How do you drive an intergalactic spaceship' was from some other random statement and response

Running from console gives this:

``` Bash
My input: power brick
ChatterBot output: How do you drive an intergalactic spaceship
```

Tried several times, but same response.

My question is why does CB not return "ensure the light is on" when I input "power brick"? Am I doing something wrong or have understood something wrongly?

Help appreciated

**Comment by vkosuri** [comment]
@shirishph Before answering your question, I would let you know chatterbot defaults methods are

1. storage adapters: [sql-storage-adapter](https://chatterbot.readthedocs.io/en/stable/storage/index.html#sql-storage-adapter)
2. logic adapter:  [Best Match Adapter](https://chatterbot.readthedocs.io/en/stable/logic/index.html#best-match-adapter)
3. response selection: [get-first-response](https://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#chatterbot.response_selection.get_first_response)

You are always getting first statement due to your response selection method is get first response from your trained object. 

You may try to use [get_most_frequent_response](https://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#chatterbot.response_selection.get_most_frequent_response) or [get_random_response](https://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#chatterbot.response_selection.get_random_response) to resolve this issue.

This information you could watch from your terminal also by enabling logging at top of the your bot configuration.

``` Python
import logging
logging.basicConfig(level=logging.INFO)
```
