### ISSUE TITLE
input adapter return statement

### ISSUE THREAD

**Issue by k3s4** [gunthercox/ChatterBot#1353]
Hello,

I have problem with process_input() function. As I have already learned this function should normally return a statement but what if input source is empty at certain time point and I don't what to input anything for chatterbot to process?

I have tried to 'return None' as I have seen in gitter example but it gives me that:
AttributeError: 'NoneType' object has no attribute 'text'

can someone explain it a little bit ?

**Comment by gunthercox** [comment]
Hi @k3s4, I apologize about the very long delay in responding to your question.

I believe the issue that you encountered was related to a bug in ChatterBot, which has since been corrected.

To answer your question, `process_input` should now always return a statement, never `None`. This was acceptable in the past because the ChatBot class had other checks to see if a response was returned from the input adapter.
