### ISSUE TITLE
Problem with twitter storage example

### ISSUE THREAD

**Issue by vojcio** [gunthercox/ChatterBot#142]
Hi!
I'm trying to make the twitter example work, but without success.
Connection to Twitter work's correctly - strace show's that chatterbox is polling data constantly from twitter, but after that it just repeat a message which were sent, so for example:

```
python3.4 bum.py
Type something to begin...
hello
hello
```

Maybe I'm doing something wrong.. But I'm stucked, and can't move forward. Code is as the twitter_storage example, without any change.

**Comment by gunthercox** [comment]
Hi @vojcio, I'm still debugging this. I can replicate it, but I believe the problem has a few factors contributing to it. For example, if a bot is created with an empty database and no results are found through twitter's api, then the only response that the bot knows to give is the user's previous input. The issue is that something should always be returned by the twitter storage adapter but this is currently not happening. I will keep you posted on a solution.

**Comment by vojcio** [comment]
Thank you @gunthercox, looking forward :)
