### ISSUE TITLE
Training data size limit?

### ISSUE THREAD

**Issue by cd-rum** [gunthercox/ChatterBot#150]
I've got a 50,000+ line JSON file for training data and it seems to hang in training. Is there a limit? Should I split it up?

**Comment by gunthercox** [comment]
For large amounts of data there is a natural limit based on the amount of hard disk space and free memory that your system has. Using the MongoDB adapter is advised for large amounts of data (https://github.com/gunthercox/ChatterBot/wiki/Storage-adapters#mongo-database-adapter).

**Comment by cd-rum** [comment]
Ah, thanks. That should help.

**Comment by korymath** [comment]
Also, check out #143

**Comment by cd-rum** [comment]
Using `ultrajson` and MongoDB solved the issue for me, a la:

```
from chatterbot import ChatBot
import ujson

bot = ChatBot("Terminal",
              storage_adapter="chatterbot.adapters.storage.MongoDatabaseAdapter",
              io_adapters=[
                  "chatterbot.adapters.io.TerminalAdapter"
              ],
              database="whatever")

f = open("all.json")
all_json = ujson.loads(f.read())
bot.train(all_json)
```

**Comment by korymath** [comment]
Any timing details on how long this took to train?

**Comment by cd-rum** [comment]
Not long. Under a minute.

**Comment by korymath** [comment]
Wonder how a big database like this will affect closest meaning adapters....

**Comment by ryanbsong** [comment]
@cd-rum What trainer did you use when training your bot? When I tried implementing the code that you had written to train my bot using a MongoDB, I used the ChatterBotCorpusTrainer and got the error AttributeError: 'dict' object has no attribute 'split'.

**Comment by ryanbsong** [comment]
@cd-rum Which trainer did you use when training the data? At first, I tried using the ChatterBotCorpusTrainer and tried training the chatterbot using the dictionary I extracted from the JSON file, but I got the error AttributeError: 'dict' object has no attribute 'split'. I then tried using the ListTrainer and converted the dictionary into a list, but while training the data, MongoDB force-quit because there were too many recursive calls during training.
