### ISSUE TITLE
Why does SQLStorageAdapter.get_latest_response take the second last as the last response

### ISSUE THREAD

**Issue by JasonZhang1991** [gunthercox/ChatterBot#1554]
Why does SQLStorageAdapter.get_latest_response take the second last as the last response, shouldn't it be the first one?

**Comment by JasonZhang1991** [comment]
Why does SQLStorageAdapter.get_latest_response take the second last as the last response, shouldn't it be the first one?

**Comment by JasonZhang1991** [comment]
Why does SQLStorageAdapter.get_latest_response take the second last as the last response, shouldn't it be the first one?

**Comment by gunthercox** [comment]
The second to last response is the newest response that the chat bot has generated. The `get_latest_response` depends on the conversation structure alternating between user and bot produced statements.

**Comment by gunthercox** [comment]
@JasonZhang1991 I think there is a chance you are correct about that. I'll be quite honest, the `get_latest_response` had some issues so I removed it entirely from ChatterBot in the 1.0 release. I highly recommend that you discontinue use of the 0.8 series because I will no longer be making changes to support it. The 1.0 release will be receiving my full attention for the foreseeable future, and if the problem you encountered still exists in the current version then I will be more than happy to do everything I can to correct it.
