### ISSUE TITLE
What are the steps of choosing a suitable response?

### ISSUE THREAD

**Issue by bufferbox** [gunthercox/ChatterBot#1710]
What approach does the chatterbot use to choose a response if I use a logic adapter?

Since Chatterbot uses the machine learning 'search algorithm' technique, then does it first do a search and finds a list of matching responses and then uses the logic adapter to choose one response from the list?

**Comment by gunthercox** [comment]
Hi @bufferbox, you are correct. ChatterBot's design is primarily search based in order to attempt to leverage database-level search efficiencies as much as possible. After retrieving a list of close matches to the input the logic adapter is only responsible for choosing a known response to that match.
