### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by mistaah** [gunthercox/ChatterBot#1753]

**Comment by gunthercox** [comment]
How did you install ChatterBot initially?

**Comment by mistaah** [comment]
First i installed chatterbot 1.0.5 using pip then it gage the following error 
Input error cant find utils from sqlachmy
Then i installed python 3.6.5 and 
 Then i downgraded to 0.8.4 using pip now it is giving the module not found error 

Before 6 months it was working fine and now my final year project is here and i am stuck plz need help

**Comment by mistaah** [comment]
I think i should uninstall all the libraries and then install them again 
What u say ?

**Comment by mistaah** [comment]
Sir i think my chatterbot version is not compatible with the code i wrote 6 months before and is not integrating with simple web socket server or python version .

Currently i had i have latest python and latest chatterbot version installed .

**Comment by gunthercox** [comment]
That sounds like a possibility. If you know what version of chatterbot you installed origionally you should be able to reinstall that specific version so that your code continues to function. Otherwise, you'l need to review the release notes and determine what changes you will need to make to you code.
