### ISSUE TITLE
Why is Chatterbot using a Response with a lower level of confidence?

### ISSUE THREAD

**Issue by brucegibbins** [gunthercox/ChatterBot#1926]
Hello.
This is a two part question. So sorry in advance. But I believe that the solution may be related to both parts. 

I suspect that I have got something wrong at my end and it is probably training related. The issue I am having is non-relevant responses appearing and upon investigating the logs it appears that between two possible responses - one with a lower confidence level is being selected.

The setup is a Windows based Django 2.x project with a ChatterBot based Web App within the project all using Python 3.6.x. I used the example Django integration from the the ChatterBot documentation (my thanks for the doco).

I built a small training script that loads the English portion of the Corpus. I also added a custom file to this set to start hosting questions and responses relevant to the project.

All files appear to be loaded and I can see statements etc in the SQLITE3 database.

### Question Part 1.

As per the  attached image of a log exert. I asked a question along the lines of "What Cybersecurity Policies does BLAH use?" Where BLAH was replaced with our company name. This exact question is in the corpus training .yml file. As you can see it seemed to find a better match with "How does a computer work?" 

My guess is that the word "does" seemed to sway this. But never the less there were heaps of other words within the phrase that should have resulted in a better match.

Question Part 2.

I still have not got my head around what I am calling "Response Feedback Training". By this I mean, the ChatterBot form responding to a question I type. BUT then I somehow tell it that the response was incorrect and either for it to have another go or I supply the correct response and it then associates that with the initial question. 

I suspect I need to build a purpose specific feedback python script that I then use outside of the Django ChatBox web page (similiar to training (train.py) script). I run this script from the CLI and it accepts user input, asks for a response and then goes into some type of "ok"/"Not Ok" condition when the response is presented.

Am I on the correct path with this? Or is there a more intuitive, in built process I should be following such that when it is released to the users they can use the Django supplied form to help it learn better.

The whole purpose of this is to help staff respond to requests for information about the company across a number of business units and I'd like to try and provide something that grows with continual use but have the responses fairly accurate based on my initial statement training.

### Log Exert

![qanda2](https://user-images.githubusercontent.com/16873240/76037326-62763780-5f92-11ea-99f6-87fa6af4bf20.png)

### Django Settings for ChatterBot are:

![qanda3](https://user-images.githubusercontent.com/16873240/76037599-327b6400-5f93-11ea-9eac-485a155a7d7b.png)

### train.py

![qanda4](https://user-images.githubusercontent.com/16873240/76037703-7706ff80-5f93-11ea-82c1-9433ded43bab.png)

**Comment by gitCommitWiL** [comment]
Are you using the development version or the last release (ver. 1.0.5)? If you are using 1.0.5 (or lower), it looks like the issue is here in best_match.py:


        search_results = self.search_algorithm.search(input_statement)

        # Use the input statement as the closest match if no other results are found
        closest_match = next(search_results, input_statement)

        # Search for the closest match to the input statement
        for result in search_results:

            # Stop searching if a match that is close enough is found
            if result.confidence >= self.maximum_similarity_threshold:
                closest_match = result
                break

        self.chatbot.logger.info('Using "{}" as a close match to "{}" with a confidence of {}'.format(
            closest_match.text, input_statement.text, closest_match.confidence
        ))

`closest_match` takes the first item from search_results, which in your case would have been the match with the lower 0.34 confidence score. Since you didn't specify the `maximum_similarity_threshold`, by default it will be 0.95, neither of which your results meet.  As a result, the condition inside the for loop is never met and so `closest_match` is never set to the match with the higher confidence. However, `closest_match` still has a value; the original match with 0.34 confidence, and hence your logs.

The development branch fixes this:

        search_results = self.search_algorithm.search(input_statement)

        # Use the input statement as the closest match if no other results are found
        closest_match = next(search_results, input_statement)

        # Search for the closest match to the input statement
        for result in search_results:
            closest_match = result

            # Stop searching if a match that is close enough is found
            if result.confidence >= self.maximum_similarity_threshold:
                break

        self.chatbot.logger.info('Using "{}" as a close match to "{}" with a confidence of {}'.format(
            closest_match.text, input_statement.text, closest_match.confidence
        ))

So you can either: modify your best_match.py, create your own logic adapter that's pretty much identical to best_match but with the fix, or use the development version. I'd recommend using the development version; a lot of things seems to be working better (at least in my tests), and spaCy helps a lot too. Though, you may have to modify the requirements.txt in order to take advantage of the newer versions of spaCy.

I haven't really looked into providing feedback for the bot so I don't think I can really help with the second question. Are you looking to do something like [this example?](https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py)

**Comment by brucegibbins** [comment]
Thanks @gitCommitWiL. really appreciate the detailed reply. I will use the Development version as it also sounds I may get a better experience with all around responses. 

You are also correct, and it is the example I am trying to mimic. In fact I stumbled across the example and will see if I can incorporate that somehow into what I am doing.

Again.... Many thanks
