### ISSUE TITLE
Chat logs for multiple instance of chatbot

### ISSUE THREAD

**Issue by futetest** [gunthercox/ChatterBot#195]
Hi

I'm trying to create logs of the conversation that instances of chat bot had had with different people and store it into a database. I know how the knowledge base works for the chat bot and its database implementation as well. What i want to do is store the logs into a database in order to monitor the chats it had with different people with their session id or something to differentiate between them.

It'd be great if someone could help me with it.

**Comment by gunthercox** [comment]
You may be able to use the [`extra_data`](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/conversation/statement.py#L32) attribute on statements to store this information in your database. This method is currently undocumented because it is not being directly used anywhere in the code base. Essentially it just allows extra information to be stored in the database attached to a statement.

Although ChatterBot currently does not support tracking conversations it has with different people, I originally added the extra-data feature to do something very similar to what it sounds like you want to achieve.

Also note that #38 covers a bit of this as well with the proposal for a `persona` object to represent the users that the chat bot interacts with.
