### ISSUE TITLE
Python 3.8.1 error!!

### ISSUE THREAD

**Issue by Priyam1418** [gunthercox/ChatterBot#1986]
**Please provide the versions compatible with Python Version: 3.8.1**

Chatterbot Version: 1.0.2
Chatterbot-Corpus Version: 1.2.0
SQLAlchemy Version: 1.2.19
I'm using these versions for my project but it is showing error while running a simple example.
![error](https://user-images.githubusercontent.com/63399260/83359526-5a167880-a398-11ea-8644-79fd4ebfd269.JPG)

Details of Versions:
![issue](https://user-images.githubusercontent.com/63399260/83359476-16237380-a398-11ea-85fa-0c079f7002f9.JPG)

**Comment by gunthercox** [comment]
I haven't tested with Python 3.8 yet, but I'm really excited that you are using the latest version. This issue looks very similar to another one that was reported: #1968

So that I can try to keep ChatterBot's issue tracker as clear and focused as I can I'm going to close this one off as a duplicate.

**Comment by gunthercox** [comment]
Duplicates #1968
