### ISSUE TITLE
How to timeout Chatterbot.get_response()

### ISSUE THREAD

**Issue by riverscuomo** [gunthercox/ChatterBot#2069]
Does anyone know how to return None if a Chatterbot.get_response() call takes more than 15 seconds? In some cases, I'm not getting a response for 25 seconds and I think that's causing timeout errors on Heroku. 

Update: I've noticed that the 25 second responses are the inevitable result of any input that contains a digit.

**Comment by nrcrast** [comment]
It may be easier to adjust your application such that chatterbox talks over websockets or something like that instead of HTTP. It doesn't seem that there's a way to configure any sort of timeout. 

Another method would be to run chatterbot on a separate thread, essentially building a chatterbot "service", then wait on a mutex with a timeout for a response.

**Comment by riverscuomo** [comment]
@nrcrast Thanks. I did try multiprocessing.Manager() but that seemed to reinitialize Chatterbot and the database connection with each call. I saw something about queues so maybe I'll try that next if I need to. For now the problem is solved because I don't call Chatterbot.get_response() if the message has a digit in it.
