### ISSUE TITLE
MongoDB few questions 

### ISSUE THREAD

**Issue by PaarthBatra** [gunthercox/ChatterBot#21]
Few questions 
Once we have mongo db to replace flat files conversations 

1. Do anyone who is using this project need to install its own instance of mondodb and have to open mongod.exe on their machine ?
2. Will it replace flat files or can we have both flat files and mongodb in such a way if someone dont have db installed can still use flat files conversations ?
3. Do we still need to specify logfiles directory ?
4. How are we going to add default conversations to mongodb for every new installations ?

**Comment by gunthercox** [comment]
Let me know if I need to clarify any of these. Also feel free to object to any of the planned changes, I realize that running local database might not always be convenient and while I'm not sure if there is any workarounds, I am not opposed to attempting to maintain flat file support of some kind. I want this project to be as useful as possible for everyone so any feedback is extremely helpful.

**1. Do anyone who is using this project need to install its own instance of mondodb and have to open mongod.exe on their machine ?**

Correct, the chatterbot needs a database instance to connect to. For windows `mongod.exe` needs to be running. [[docs link](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/#start-mongodb)]

**2. Will it replace flat files or can we have both flat files and mongodb in such a way if someone dont have db installed can still use flat files conversations ?**

In the branch i've been working on, I replaced the flat file access completely because I didn't have a way to maintain the ability to store object references for each statement. Future changes that need to be made to this program really require a database of some kind, and csv files don't provide an adequate level of flexibility. For instance, the database implementation will allow the bot to query responses that are specific to a single user, or recall conversations that it had with a particular person.

**3. Do we still need to specify logfiles directory ?**

Nope, this won't be needed.

**4. How are we going to add default conversations to mongodb for every new installations ?**

For this, I've added a method called `train()` which takes a list of usernames and statements as a parameter. I've included a sample below. In the future, it should also be possible to pass a file in as a parameter to the training method.

```
from chatterbot import Terminal
from chatterbot.algorithms.engram import engram

# Create a new terminal chat bot and use the engram algorithm to select responses.
chatbot = Terminal(engram)

conversation = [
    ["user", "Hello"],
    ["salvius", "Hi there!"],
    ["user", "How are you doing?"],
    ["salvius", "I'm great."],
    ["user", "That is good to hear"],
    ["salvius", "Thank you."],
    ["user", "Your welcome."],
    ["salvius", "Sure, any time."],
    ["user", "Yeah"],
    ["salvius", "Can I help you with anything?"]
]

# Train the chat bot on these know conversations
chatbot.train(conversation)

# Start the terminal session
chatbot.begin()
```

**Comment by PaarthBatra** [comment]
That clears most of my doubts and Sorry about the typo Mongo -> Mondo . 

Implementation of DB as a replacement of flat files looks great . 
Only thing i can suggest is we should create a CSV file or rather have a database dump ( like database dump in oracle ) by which anyone who will use this library can import database dump and can use it with some of default conversations and we must include that in the readme section so it becomes clear .

I am not mach familiar with MongoDB as of now , installed it yesterday , its easy to install and yes db implementation should be far more better than flat files .

**Comment by kevin-brown** [comment]
Once the MongoDB implementation settles down, and we have a semi-reasonable API, it might be useful to extract it out into an adapter, so the data storage/source location could be swappable.  Considering there are different storage types out there for conversations (IRC chat logs come to mind, among many others), it would be useful to be able to still fall back on different storage engines instead of relying on just a single engine.

**Comment by gunthercox** [comment]
I'm closing this one off since commit f26da1bef066455c0526431fb3d9d7179ddece29 introduces an adapter class that can be used to incorporate other database types.
