### ISSUE TITLE
OSError: [E941] Can't find model 'en'.

### ISSUE THREAD

**Issue by Danycraft98** [gunthercox/ChatterBot#2128]
I am using Chatterbot v1.1.0 and spacy v3.0.3. I am getting this error:

`OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0. To load the model, use its full name instead:`

**Comment by intercontoni** [comment]
Tray uprade chatterbot to 1.0.8

Desinsintall spacy 3.0..

Install this spacy..

pip install spacy==2.3.5 en_core_web_sm en

python -m spacy download en
python -m spacy 2.3.5 link en_core_web_sm en --force

The problem here seems to be that Chatterbot hard-codes spacy.load("en") in its code, specifically in chatterbot/tagging.py. In spaCy v3, loading a model from a shortcut like en is deprecated, because this usage is misleading: there are many different en or es models, so it should always be clear which package is being loaded. For example, en_core_web_sm or es_core_web_sm.

So this is something that needs to be updated by Chatterbot in the future to support the new spaCy v3.

In the meantime, you can install spaCy v2 that still supports the shortcuts:

pip install spacy==2.3.5
