### ISSUE TITLE
note: This error originates from a subprocess, and is likely not a problem with pip.

### ISSUE THREAD

**Issue by maazirfan** [gunthercox/ChatterBot#2315]
facing above error while installing on win 11

**Comment by MrKitten1753** [comment]
I am facing the same error too; I did some fiddling and found that the problem is most likely with how it installs the dependencies it needs. The four problem areas are Spacy, Blis, Preshed, and Thinc. I tried manually installing these dependencies after running pip install chatterbot --no-deps, but spacy seems to be the only library I could not install.

Maybe they will update it to work with newer versions of each dependency?

**Comment by maazirfan** [comment]
!pip install chatterbot==1.0.4
!pip install PyYAML==5.1
install by using the above version it will be helpful.
