### ISSUE TITLE
whether the confidence setting is too low, and re-run issue

### ISSUE THREAD

**Issue by PengTedShen** [gunthercox/ChatterBot#235]
Hi @gunthercox 

Thank you for great work. ChatterBot is in very good quality and easy to use. After used for a while, I found three issues which would like to discuss with you.

1. After added "TheIDontKnowAdapter", about codes below:
    ```
    if confidence < 10:
            return 1, default_response
    return 0, closest_match
    ```
whether the value of confidence is setting too low? normally,  it is easy to pass default_repsonse and return as closest_match

2. within "base_match.py", the codes are 
       ```
       if response_list:
            response = self.break_tie(response_list, self.tie_breaking_method)
        else:
            response = self.context.storage.get_random()
       ```
so if response_list is empty, you pick up answer randomly. I changed to 
       ```
        else:
            response = self.context.storage.update(closest_match)
       ```
what do you think? is there any better way when response_list is empty?

3. After re-run for several times, I found the output part can have wrong answer even the answer come from previous question part when there is no related input from corpus data . For every first run, the answer was correct, then after "database.db" was built,  program will search even all the records within database, so provided the previous question part to output answer when the  fuzz confidence is higher.

**Comment by gunthercox** [comment]
Hi @PengTedShen, for your question:

1. It is possible that 10 is not the most optimal value for that code example. Feel free to adjust it as needed.
2. The method call to `self.context.storage.update(closest_match)` will return the updated statement that is passed in to the method. Although, it's meta data may change, the statement text will be the same. I would advocate keeping the random response fallback for now rather than just returning the input as a closest match, but I'm open to other suggestion.
3. Note that the chat bot also continues to learn as you talk to it, so it may be learning additional response options from your input. If this functionality is not desired then it is possible to but the database into read-only mode by specifying `read_only=True` when initializing the chat bot.

**Comment by PengTedShen** [comment]
Thank you for your reply. About point 2, I will discuss with you if I could have some suggestions after study codes further.
