### ISSUE TITLE
Missing "," in linguisticKnowledge_pt-BR.json

### ISSUE THREAD

**Issue by davizucon** [gunthercox/ChatterBot#249]
Hi,
   There is a missing "," in file , chatterbot/corpus/data/Portuguese/linguisticKnowledge_pt-BR.json 14:34

Thanks

**Comment by gunthercox** [comment]
Thank you, I believe this has been recently corrected and will be fixed in the next release of ChatterBot. The commit https://github.com/gunthercox/ChatterBot/commit/1ed1afad690ee5c4e10d81f285dcb5ddb2a4bad1 appears to contain the fix.

I'm going to close this issue. Feel free to reopen it if that was not a fix for the error you were refering to.
