### ISSUE TITLE
How can we have a Null response when statement doesn't exist but confidence is good

### ISSUE THREAD

**Issue by alekaizer** [gunthercox/ChatterBot#367]
Hi @gunthercox, using ClosestMeaning and ClosestMatch adapters output some weird-ish sometimes:
Let's take this dataset:

```
  pair = ['what is your address','R2D2 AI Street, TUXVILLE, PC-Land']
```

and chatterbot init this way:

```
  bot = ChatBot('LC',
          logic_adapters=[
                "chatterbot.adapters.logic.ClosestMatchAdapter",
                "chatterbot.adapters.logic.ClosestMeaningAdapter"
          ])
```

Bot is trained with **pair**

```
  bot.train(pair)
```

and let's input these:

```
INPUT
print(bot.logic.process(bot.input.process_input('what is your name')))
print(bot.logic.process(bot.input.process_input('what is your address')))
print(bot.logic.process(bot.input.process_input('where are you located')))

OUTPUT
(0.74, <Statement text:R2D2 AI Street, Motherboard, PC-Land.>) <-- (1)
(0.93, <Statement text:R2D2 AI Street, Motherboard, PC-Land.>)
(0.62, <Statement text:R2D2 AI Street, Motherboard, PC-Land>) <--- (2)
```

**1** Is obviously wrong but the confidence(**0.74**) is even higher than **2**'s(**0.62**)

So my question is how can I have the bot knows that **1** is wrong but **2** is right ?

**Comment by gunthercox** [comment]
The solution; more training data. Because `'what is your name'` is very similar to `'what is your address'` (they both share a common `what is your`) the logic adapters are picking it up as a possible response. However, if you train your bot with other variations of the input, something like: `['where are you located','R2D2 AI Street, TUXVILLE, PC-Land']`, then it will generate a higher confidence for inputs similar to that text.

**Comment by alekaizer** [comment]
Oh okay, I'll try that out ! thanks @gunthercox
