### ISSUE TITLE
key with empty in_response_to field

### ISSUE THREAD

**Issue by alekaizer** [gunthercox/ChatterBot#377]
@gunthercox I am sorry if this question has already been asked before, I didn't know how to express the my search query

So the question is about the storages, I can see that we have two entries per Statement:

1. with empty **in_response_to** field
2. with filled **in_response_to** field

Example:
`{
    "_id": {
        "$oid": "58189c46620c9c7d49db1c59"
    },
    "text": "Welcome to Tuxville",
    "in_response_to": []
}
`
`{
    "_id": {
        "$oid": "58189c46620c9c7d49db1c59"
    },
    "text": "Welcome to Tuxville",
    "in_response_to": [
        {
            "text": "hey",
            "occurrence": 1
        }
    ]
}`
    
and when I check the storage adapters I saw this in the **train** method:
`self.storage.update(statement, force=True)`

so I expected the first object to be updated, but it's creating a new object

Maybe I'm missing something in the flow !

**Comment by gunthercox** [comment]
Hi @alekaizer, how are you getting these results? I don't believe it should be possible for these two statements to exist separately. The _two_ statements you have listed are the same statement because they have the same ID. Mongo DB won't allow two objects to have the same ID and ChatterBot applies a unique index constraint to the `text` attribute of statements so two statements cannot be the same.

I might have missed something, but maybe the issue is just how you are inspecting the database?

**Comment by alekaizer** [comment]
oh sorry @gunthercox,  the $oid  it's just a copy/paste of the same object with diff value, of course they don't have the same $oid in the DB

here is a real state of the DB

`{
    "_id": {
        "$oid": "5819fbc9620c9c7d49f7f0af"
    },
    "in_response_to": [
        {
            "occurrence": 1,
            "text": "Can I ask you a question?"
        }
    ],
    "bot_id": "af2ecfc7-79ab-45a2-9200-a172c719d4f5",
    "text": "Go ahead and ask."
}`
`{
    "_id": {
        "$oid": "5819fbc9620c9c7d49f7f0ae"
    },
    "in_response_to": [],
    "bot_id": "af2ecfc7-79ab-45a2-9200-a172c719d4f5",
    "text": "Can I ask you a question?"
}`

the question is created as response and have its **in_response_to** array empty
then when it's updated it's not deleted, causing to have multiple entries with **in_response_to** being empty arrays

Hope this time I was clear :)

**Comment by gunthercox** [comment]
I _think_ this is the correct functionality. If an entry exists for `"Go ahead and ask."`, then the `in_response_to` attribute for that statement should list `"Can I ask you a question?"` as a response. The actual entry for `"Can I ask you a question?"` should have `"in_response_to": []` as empty because the chat bot hasn't learned anything in response to `"Can I ask you a question?"`.

I think the issue here might just be the wording on the attributes.
 `"Go ahead and ask."` is in response to `"Can I ask you a question?"`.
`"Can I ask you a question?"` is in response to nothing.

Let me know if this answers your question.

**Comment by alekaizer** [comment]
Yes that's the functionality, and my problem is : 
`"Can I ask you a question?"` is in response to nothing.
In that case is it relevant to store it, as there's no trigger for that statement?

I think that comes from the conversation way of training, as they have backward reference.

**Comment by gunthercox** [comment]
There are a few reasons why statements like `"Can I ask you a question?"` are stored when they have an empty `in_response_to` attribute.

1. Other data can be stored on the statement object. For example, statements can have an `extra_data` attribute that holds information generated by various adapters.
2. For data consistency. Every response has a corresponding statement that _can_ have responses.
3. From a performance perspective, it is useful to have it in case we need to list all statements known by the chat bot. If we did not do this, then we would need to traverse all statements and all statement-responses to list them.
4. Since the chat bot's database is essentially storing a graph data structure represented as the relationship between statements and responses, then it is useful to have the next statement in the graph, even if that statement has no known responses. This just tells us that there is more to learn.

I hope these help.

**Comment by alekaizer** [comment]
yes 👍 perfectly clear :)
