### ISSUE TITLE
Importing Terminal fails

### ISSUE THREAD

**Issue by asya-bergal** [gunthercox/ChatterBot#41]
The command `from chatterbot import Terminal` gives me a `cannot import name Terminal` error. This also happens with `TalkWithCleverBot` and I suspect every import except for `ChatBot`.

**Comment by kevin-brown** [comment]
I suspect this happened after https://github.com/gunthercox/ChatterBot/commit/ffebc964e4ff68103d5613188f5359b9f098ece8, which was part of the current efforts to split things up into individual modules.

**Comment by gunthercox** [comment]
These classes have been moved out of the package for the latest release. This was done in favor of keeping the main ChatBot class as abstract as possible while simultaneously introducing the concept of **adapters** for various operations.

**Example Classes**
All of the classes such as `Terminal` and `TalkWithCleverBot` have been moved into the [examples](https://github.com/gunthercox/ChatterBot/tree/master/examples) directory in the repo.

**Adapter Classes**
ChatterBot version 0.2.0 introduces the concept of adapters for three categories of operations. ChatterBot defines these three categories as **storage**, **logic**, and **io**. This change will make it possible for future modules to be created that allow ChatterBot to be set up to use any type of database, and communicate with users through any medium such as web apis.

Currently there isn't any documentation on these items since I forgot about updating the readme. I'll add thorough documentation as soon as possible.

**Comment by gunthercox** [comment]
I've updated the documentation in the readme for these changes. Please let me know if anything is unclear or could be improved.
