### ISSUE TITLE
a combination of both voice and chat

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#416]
@gunthercox is it possible to having both voice and response in a Django chatterbot? If so could you provide an example scenario here?

**Comment by gunthercox** [comment]
I think it's definitely possible, but because it's a web app the audio will have to be processed on the client's side. This might make things easier because there is likely several javascript libraries available that handle speech recognition and speech synthesis. It looks like Google Chrome has built in support for both speech recognition and speech synthesis: https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API

**Comment by gunthercox** [comment]
Hi @vkosuri, I'm going to close this ticket off. I believe your question was answered, feel free to reopen the ticket if I missed something or you still have questions.

**Comment by vkosuri** [comment]
@gunthercox thank you
