### ISSUE TITLE
ImportError: No module named settings from microsoft_bot.py 

### ISSUE THREAD

**Issue by loveJasmine** [gunthercox/ChatterBot#437]
```
rzai@rzai00:~/prj/ykdebug-ChatterBot$ python microsoft_bot.py 
Traceback (most recent call last):
  File "microsoft_bot.py", line 3, in <module>
    from settings import Microsoft
ImportError: No module named settings
rzai@rzai00:~/prj/ykdebug-ChatterBot$ 
```

**Comment by gunthercox** [comment]
Hi @loveJasmine, the reason that a `settings.py` file is not included in the examples directory is because it would contain private API keys for the various examples that require them. To use this example, you would need to register a bot on the Microsoft Bot Framework website and use the credentials given there.

Your `settings.py` file should look similar to the following:

**settings.py**
```python
Microsoft = {
    'direct_line_token_or_secret': 'xxxxxxxxxxxxxxxxx',
    'conversation_id': 'xxxxxxxxxxxxxxxxx'
}
```

**Comment by meain** [comment]
@gunthercox  Maybe we could add a dummy settings file with all the spaces for the api keys left blank? In that case the error will be something like `invalid key` than an `import error` which will be better I think.
