### ISSUE TITLE
django login screen

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#447]
I thought this could be a useful feature, if we have a nice login page for django example app.

common credentials are
```
User: chatterbot
Pass: chatterbot
```

@gunthercox can i submit PR for this request?

**Comment by gunthercox** [comment]
My original intention for the example django app was to keep it as simple as possible so that new developers could easily see the changes they need to make to add ChatterBot to their Django project. I'm not opposed to the idea of making additions, but what would the benefit of a login page be?

**Comment by vkosuri** [comment]
Usually the web services are provided using login credentials only. That's the reason i am looking into

**Comment by gunthercox** [comment]
Since ChatterBot is now supporting concurrent chat sessions, I can see the ability to log into the Django example being useful. I think a good use case might be that someone wants to test out the chat bot having two different conversations. They could make two user accounts and sign in on different browsers.

**Comment by vkosuri** [comment]
Agreed with you
