### ISSUE TITLE
 Multiple input and output adapters on a single bot instance

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#458]
I think currently chatter will send requests and response to all configured logic adapters, instead is there a possibility send one to one mapping.

For example

If user requested from twitter response should go only twitter.

@gunthercox Any idea how to achieve this task?

**Comment by gunthercox** [comment]
What action would the logic adapter be taking in this example?
Normally an input adapter would receive the input from Twitter and an output adapter send it back to Twitter.

**Comment by vkosuri** [comment]
Apologies For confusing, Is there possibility to configure multiple input and output adapters on a single bot instance?

```Python
bot = ChatBot(
    "All in One Example Bot",
    mailgun_from_address=FROM_EMAIL,
    mailgun_api_key=MAILGUN["CONSUMER_KEY"],
    mailgun_api_endpoint=MAILGUN["API_ENDPOINT"],
    mailgun_recipients=RECIPIENTS,
    input_adapter="chatterbot.input.Mailgun",
    output_adapter="chatterbot.output.Mailgun",
    storage_adapter="chatterbot.storage.JsonFileStorageAdapter",
    database="../database.db"
    
    # Hipchat
    input_adapter="chatterbot.input.HipChat",
    output_adapter="chatterbot.output.HipChat",
    hipchat_host="https://mydomain.hipchat.com",
    hipchat_room="my-room-name",
    hipchat_access_token="my-hipchat-access-token",
)
```

**Comment by gunthercox** [comment]
Right now there isn't a way to do this _exactly_. However, one simple way to achieve it would be to create two separate chat bot instances that share the same database.

**Comment by vkosuri** [comment]
Thanks, I have few other questions, if we add this features integrated into chatterbot, 

1. any consequences/issues will occur? 
2. If not any plan implementation this feature?
3. Will it benefited to chatterbot?

**Comment by gunthercox** [comment]
At one point, this feature was actually added: https://github.com/gunthercox/ChatterBot/pull/116
I removed it because there wasn't a way to specify where an input from one source should be returned to (So for example, input from Twitter should return output to Twitter).

I don't think this functionality would benefit ChatterBot. Supporting multiple inputs and outputs really increases the complexity of getting and returning responses. As I mentioned before, using multiple chat bots should provide the same functionality, but with no changes required to the code base.

**Comment by vkosuri** [comment]
Great and thank you
