### ISSUE TITLE
The data received from twitter is not copied to the database

### ISSUE THREAD

**Issue by engineer34** [gunthercox/ChatterBot#484]
I am creating a twitter bot with your project but The data received from twitter is not copied to the database. self.storage.(statement) part is not working ?

**Comment by vkosuri** [comment]
@engineer34 Could you please let me know type adapter are you using for example Terminal/django/etc

**Comment by engineer34** [comment]
storage_adapter = "chatterbot.adapters.storage.TwitterAdapter"

**Comment by gunthercox** [comment]
@engineer34 I think you are using an old version of ChatterBot. The twitter storage adapter has been removed because it had a number of issues. There is a new training module that replaces it and it should work much better: http://chatterbot.readthedocs.io/en/latest/training.html#training-with-the-twitter-api

**Comment by engineer34** [comment]
I try this example but I get an error message :
ImportError: No module named input

**Comment by gunthercox** [comment]
Maybe that module doesn't exist in the version you have?

**Comment by engineer34** [comment]
thank you so much
