### ISSUE TITLE
Terminal Example

### ISSUE THREAD

**Issue by shambolic** [gunthercox/ChatterBot#50]
probably a simple oversight, but trying to run your terminal example i get the following error:
`AttributeError: 'ChatBot' object has no attribute 'get_input'`

have successfully imported the module and 'dir'd around the objects a bit, but can't see a get_input method anywhere. do i need to explicitly import Terminal?
thanks!

**Comment by gunthercox** [comment]
Sorry, this is because the version of ChatterBot on PyPi is behind the version of ChatterBot on master. I plan on doing a release of the next version of ChatterBot within the next week. Until then I recommend downloading the current copy of the repo from github, and installing it locally via `pip install . --upgrade`.

I apologize for the inconvenience, I hope this solution helps.

**Comment by shambolic** [comment]
great. that's done it.  sorry if that was documented elsewhere.  keep up the good work!
