### ISSUE TITLE
which dialogue algorithm is adopted in this project?

### ISSUE THREAD

**Issue by muatik** [gunthercox/ChatterBot#64]
I am curious about which of the following features are available;

* enriching or at least retaining a context during a dialogue 
* learning from humans
* making prediction or/and deduction based on available knowledge

Another thing is: Is it just simple statement matcher in which user questions and bot questions have to be the exactly same?

For instance, suppose i trained the bot with:
q: "where is the post office? "
a: "it is right behind you"

and user may ask like this:
q: "looking for the post office"

What will the chatbot give to the user?

**Comment by gunthercox** [comment]
ChatterBot currently supports two different dialogue algorithms.

The first is the _closest match_ algorithm that determines the similarity between the statement provided by the user and a set of known statements. For example, based on the sample input you provided, there is a 65% similarity between `"where is the post office?"` and `"looking for the post office"`. The closest match algorithm selects the highest matching known statements and returns a response based on that selection.

The second is the _closest meaning_ algorithm. This algorithm uses the wordnet functionality of [nltk](http://www.nltk.org) to determine the similarity of two statements based on the path similarity between each token in each statement. The sum of the path similarities is used so that the statement that has the closest path similarity (basically the closeness of synonyms) is returned.

* In the case of both algorithms and the training examples you provided, the input of "looking for the post office" would match close enough to "where is the post office?" to return "it is right behind you".

***

So, to answer your questions about what functionality is available:

- **enriching or at least retaining a context during a dialogue**  
(Currently not present.) ChatterBot **does** retain a copy of the current conversation and it a parameter that is provided to all logic adapters. However, it is currently not used. I have plans to create a new logic adapter that uses the context of the current conversation to alter the decision of what result is returned. This feature is most likely to be added next.

- **learning from humans**
(Yes) ChatterBot does have a readonly mode where it will not learn, however by default the ChatterBot will add to it's known selection of responses as an individual communicates with it. It maintains the context of what the statement was and what it was in response to. It also records the number of times a given response has occurred, a useful metric when selecting the most likely response to a given statement.

- **making prediction or/and deduction based on available knowledge**
(Yes) The logic that is currently available is more deduction based, but it just comes down to how each selection is chosen in a given response algorithm. In all cases, the current selection of response algorithms always go with the most likely response.

***

Additionally, creating new response algorithms is fairly simple. To create one, just define a class that completed this interface:

```python
class MyLogicAdapter(LogicAdapter):
    def get(self, text, statement_list, current_conversation):
        # TODO
        return selected_statement
```

**Comment by muatik** [comment]
:+1: very detailed explanation. I couldn't find this information anywhere, maybe you can consider to present it in this project's wiki pages.

**Comment by gunthercox** [comment]
Thank you, I am planning on making these updates to the documentation soon.

**Comment by gunthercox** [comment]
I have updated these sections in the wiki. Thank you for posting these questions, please let me know if there is anything else I can improve or clarify.

**Comment by muatik** [comment]
I near future, I may make some contribution to this project because I am planning to use something similar to  chatterbot in one of my spare time works. Thank you.
