### ISSUE TITLE
While installing ChatterBot-Voice, ChatterBot uninstalls

### ISSUE THREAD

**Issue by elviraC** [gunthercox/ChatterBot#644]
Hello,

I wanted to test out the ChatterBot-Voice. But when I used the "pip install chatterbot-voice" command, it uninstalled my chatterbot 5.0, which is really annoying. I had to uninstall chatterbot-voice and chatterbot, to reinstall chatterbot to get chatterbot to work again.

How can I install chatterbot-voice, without it uninstalling chatterbot..?

**Comment by gunthercox** [comment]
Hi @elviraC, this is happening because the [requirements.txt](https://github.com/gunthercox/chatterbot-voice/blob/master/requirements.txt) file in the `chatterbot-voice` package is pined for `ChatterBot>=0.3.5,<0.5.0`. It needs to be updated, probably to something like `ChatterBot>=0.4.0,<0.6.0`.

Feel free to make a pull request with the change if you want to contribute. Otherwise I will make the change as soon as I can.

**Comment by gunthercox** [comment]
I've updated the version requirements. https://github.com/gunthercox/chatterbot-voice/commit/9fdb29bd1ee5bdbcbe72af8cf386bd0760329fa6

The change will be available when I release the next version of the `chatterbot-voice` package.

**Comment by gunthercox** [comment]
The next version of the `chatterbot-voice` package has been released to the Python package index. Please upgrade to the latest version to receive this fix.
