### ISSUE TITLE
Forum or discusgroup?

### ISSUE THREAD

**Issue by BLCKPSTV** [gunthercox/ChatterBot#703]
Is there a discusgroup or forum where there can be talked about chatterbot?

I'm having problems importing custom corpus in the Djange example on heroku. And I don't want to bother the Issues everytime.

Would be nice and good to create a community.

**Comment by gunthercox** [comment]
Currently there isn't one. I wouldn't be opposed to creating a community forum for ChatterBot.

Do you have any recommendations or examples of other projects that do a good job of this?

**Comment by BLCKPSTV** [comment]
Stackoverflow - but there's a barrier crossing for beginners. (They policy of comments/posting/etc...)
Google Groups page? - Openface has one and I got answers pretty quick though not a solution and there's a better chance of solutions with stackoverflow. (do to the same policy)
Hitchhike on a pythonforum or in my case a django forum... 
I would like to contribute, but my knowledge isn't sufficient to act as a helpful wizard in chatterbotfora/community. I would mostly ask the questions myself. But this wil be in a long run helpful for other beginners at python, django etc... and this in using chatterbot.

**Comment by gunthercox** [comment]
Right now I think I'm leaning towards Stack Overflow. Google even uses it for many of their Python packages. I do agree that there is a barrier for beginners but I think that may possibly be a positive element because there are a lot of other resources out there for absolute beginners when it comes to programming. I may be wrong about this, but from my perspective it is somewhat beneficial if some of the beginner 
questions get filtered out. Maintaining open source projects can be a lot of work and it is easier if the maintainers can focus on fixing bugs and evolving the software.

I think the massive community backing Stack Overflow would also be helpful for answering some of the more general questions that come up.

Right now I don't have enough points on Stack Overflow to create a `chatterbot` tag. I'll look into seeing if I can find someone to create it. If not I will work on answering some questions on there until I have enough points to create the tag.

**Comment by vkosuri** [comment]
@gunthercox Master, Can i ask them http://stackoverflow.com/contact here?

**Comment by gunthercox** [comment]
Feel free to.

**Comment by rajasimon** [comment]
Well I have some reputation [Raja Simon](https://stackoverflow.com/users/3762142/raja-simon). Shall I create tag in SO. Can't wait to bring this community to SO. So exiting.

**Comment by gunthercox** [comment]
@rajasimon If you can create the `chatterbot` tag, that would be very much appreciated.

**Comment by vkosuri** [comment]
:+1:

**Comment by rajasimon** [comment]
Thanks. I created it. I'm editing as much question now to include chatterbot tags. 

https://stackoverflow.com/questions/tagged/chatterbot

**Comment by BLCKPSTV** [comment]
Hey, awesome that this is becoming something. Would you mind asking a thourough explanation to use a own corpuses and activating them on the django platform?

**Comment by gunthercox** [comment]
@rajasimon Thank you. This is going to make a huge difference in how questions are able to be asked and allowing them to be responded to.

**Comment by gunthercox** [comment]
@BLCKPSTV There is a ticket currently open requesting more documentation for ChatterBot's Django integration. I will be adding additional documentation as soon as possible. Feel free to open a ticket if you think any examples or additional explanations would benefit the project documentation.
