### ISSUE TITLE
Create SQL tables automatically if none exist

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#741]
Currently it is required for `create=True` to be set when using to `SQLAlchemyDatabaseAdapter` for the first time so that it creates the tables in the database. This should only need to happen once.

- A check should be added so that when the storage adapter is initialized it checks to see if the tables exist.
- If the tables do not exist, then they should be created.
- The `create=True` parameter should be removed.

**Comment by apoorv-mishra** [comment]
Hi @gunthercox , I am relatively new to open-source. I just wanted to validate my approach to achieving what you mentioned above. I think of creating a global variable in `sqlalchemy_storage.py`, say `table_created` and initialising it to `false`, then within the `__init__` method of `SQLAlchemyDatabaseAdapter` class, we check whether `table_created` is `false`. If so, we create the tables by calling `create()` method, else, we don't. Am I right?(I may be completely wrong, since, I am new to this)

**Comment by gunthercox** [comment]
@apoorv-mishra My apologies for the delayed response. It is usually best to avoid the use of global variables unless absolutely necessary. I'm still familiarizing myself with how SQL Alchemy works and at this point I don't have an accurate recommendation that I can provide. I believe that the part you mentioned about checking if the table is created upon initialization is correct. If I were going to implement this I would likely investigate a solution following that notion.

**Comment by apoorv-mishra** [comment]
@gunthercox Alright, thanks.
