### ISSUE TITLE
SVO Logic Adapter

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#78]
It turns out I made a minor mistake going with Pattern. Since it is not available on Python 3.x yet, we will need to change the logic adapter to use another SVO triplet identifier. We can use nlpnet, but that contains a fairly large dependency file which I am not sure is worth it. If that doesn't work, we could use a simple SVO triplet identifier I created using NLTK's built-in POS Tagger, but I am not confident in its ability to correctly identify the subject, verb, and object of complex sentences.

@gunthercox what course of action would you prefer?

**Comment by gunthercox** [comment]
Sorry, I noticed this too after merging yesterday and didn't get a chance to respond. It looks like tests didn't run on the pull request so I never got a notification about the python 3 issue.

Nlpnet had a few python 3 compatibility issues as well that I was able to open a pull request to fix
(https://github.com/erickrf/nlpnet/pull/18). I also agree that the dependency file is rather large for nlpnet and I noticed that it uses c extensions for faster processing, the issue is that it may also cause this library to fail to install in some windows environments.

I would be interested to see if it was possible to accomplish SVO triplet identification with NLTK which has excellent support across platforms and python versions.

For the time being, I am going to move the last commits for the SVO adapter to different branch until we can get these issues corrected.

**Comment by DarkmatterVale** [comment]
Yes, and for that reason I'm leaning towards not implementing nlpnet. You can check out my current implementation here https://github.com/DarkmatterVale/regex4dummies/blob/master/regex4dummies/semantic_parsers/nltk_parser.py . It is a little rusty, but with some improvement we might be able to get it to work solidly for a large percentage of sentences.

Good idea to move the commits over to a new branch. Sorry I didn't get the Travis-Ci build on; forgot to set it up until this morning when I saw the index error.

**Comment by gunthercox** [comment]
That's ok, new branch is up at https://github.com/gunthercox/ChatterBot/tree/svo

**Comment by DarkmatterVale** [comment]
Thank you for moving it. I will close this issue since it is not affecting the main branch anymore.
