### ISSUE TITLE
Why did the chatterbot respond slower?

### ISSUE THREAD

**Issue by narnikgamarnikus** [gunthercox/ChatterBot#839]
I used the ubuntu corpus trainer.
I just did usual training (I use MongoDB).

The bot sends messages to the web interface via web sockets. Earlier, when there was no data, he responded instantly. Now you need to wait 5-10 seconds until he answers.

I understand that this problem is related to mongo and not to the chatterbot, but is this really normal ?
Or am I the only one who has this problem?

**Comment by gunthercox** [comment]
It takes longer because there is more data to process when selecting a response.

**Comment by sal48** [comment]
@gunthercox, yeah, but this is a problem. It's the problem I currently have with my chatbot. What is the best way to handle this? Should I load everything from disk and just keep it in RAM? I've ran the problem to ground, and I see that the most time is spent when it gets all response statements from the DB. I had this issue both with MongoDB and SQLite. (best_match.BestMatch.get method)

What is the best way to tackle this? Should I just create a new Storage adapter that keeps all of the convos in RAM? I'll try to keep my answer general, so it can be committed and used. Let me know your thoughts, and I'll see if I can get better timings by keeping the data structures loaded in RAM.

**Comment by narnikgamarnikus** [comment]
@gunthercox, It is obvious.
Also, I see how my processor is overloaded, when searching for an answer.

**Comment by sal48** [comment]
@narnikgamarnikus Actually, I looked deeper at the problem. Retrieving data from the tables doesn't take any time at all. (Putting all of the cornell data mentioned above takes about 100 MB, and it's accessed really quickly.)

The real issue is finding a close match. Out of the 88 seconds that it took to retrieve an answer, 72 seconds were spent iterating over the statement list and using the comparison functions. logic.best_match.get function. Specifically, the part where it iterates over the statement_list structure. Maybe adding a check with something like, if confidence over some threshold, like .8, then exit the loop and return that statement. This will be more easily generalized as a parameter that can be passed in on startup.

**Comment by sal48** [comment]
Also, @narnikgamarnikus, MongoDB is a NoSQL database, and it's perfectly fine for production projects.

However, if you'd prefer to get away from the storage options available, you can code a storage adapter. It's really not too bad, there's only a handful of methods you need to code. (It's mostly code to connect to your instance.)

**Comment by narnikgamarnikus** [comment]
@sal48, Maybe it makes sense to write in the documentation about the threshold values for storing the number of records, after which the bot starts to slow down significantly?

**Comment by gunthercox** [comment]
This issue is a problem that I am aware of and working to fix. My plan is to reduce the amount of statements that need to be analysed when searching for a match. To accomplish this I am going to modify the training process so that it categorizes each statement. The categorization process will be flexible and will even allow developers to add their own categorization functions. Here is a quick example of how this will improve performance:

1. User enters input: "How are you?"
2. Chat bot categorizes the input as a `question`.
3. Chat bot adds query parameter that specifies that the returned statements must be categorized as an `answer`. As a result, a much smaller set of possible responses is returned and processing time is reduced.

**Comment by sal48** [comment]
@gunthercox I think that's the correct direction, but the codebase seems pretty far from that point. I'll try experimenting with different confidence thresholds tonight, as the chatbot simply isn't production ready when it takes 80 secs to respond.

@narnikgamarnikus The threshold value seems to vary on application. For instance, if you're running a chatbot for a company that needs to answer technical troubleshooting issues, it may be permissible for a 30 second response. I want to stand up the chatbot because it's so damn cool, so in my case, I don't want users waiting more than 10ish seconds. I'm gonna add some javascript to my page and possibly just have a timer that shows "Chatbot is typing..." while I await the response, so it feels a little more natural.

I'll report my findings, and we can see what part of my code we'd like to add to the repo.

**Comment by vkosuri** [comment]
@gunthercox Master, Looks good to me the above approach. I have few question on above process.

If the entire corpus database has question and answers,  For example UbuntuCorpus.

the above approach will improve request and response time? how could be the approach such corpus models?

**Comment by Olagsfark** [comment]
I sure hope the time lag issue is fixed. the timing on my bots is way too much for production. 
I really hope to see this fixed. 
Anyways, @gunthercox great JOB!!! Truly great job Man!!!!

**Comment by mymusise** [comment]
@gunthercox  Hi, if bot will find a response from all dataset everytime, why not make a preproccess after training and filter the statement just need not all when calling `get_response`. For example `Inverted index`.

**Comment by gunthercox** [comment]
@mymusise We are working on changes that will prevent the full dataset from needing to be searched each time a new input is received. #924 and #925 have further details on what changes will be made.

**Comment by chasingML** [comment]
@narnikgamarnikus @sal48  hi,bros, have u solved the problem of efficiency? my bot used only about 3M data with mongodb and response time about 41s , it is really too slow. can u share some experience about improving efficiency?

**Comment by phpmind** [comment]
Did anyone use elastic search? ElasticSearch is really fast for searching text?  It happens because everything comes from RAM.

**Comment by gunthercox** [comment]
I'm going to close this off. The tagging and filtering ticket I described is being tracked as #925

**Comment by zxsimple** [comment]
@narnikgamarnikus， you probably hasn't install python-Levenshtein， please check whether [https://github.com/gunthercox/ChatterBot/pull/1158](https://github.com/gunthercox/ChatterBot/pull/1158) is helpful or not
