### ISSUE TITLE
How to add our chatbot to the server

### ISSUE THREAD

**Issue by anilneeluri** [gunthercox/ChatterBot#884]
I want to add my chatbot in the server. What is the best way to do it?

**Comment by AxelAli** [comment]
check Flask Chatterbot
[https://github.com/chamkank/flask-chatterbot](url)

**Comment by gunthercox** [comment]
@anilneeluri This is kind of a vague question because it doesn't really specify any details about the kind of server you are using. I'm going to assume you are intending to run ChatterBot as a web application?

I'm going to open a pull request that adds some documentation on this. It would be awesome if you could review / comment on it to make sure that I cover everything you need. This is a good "getting started" question and it has come up before so I think its a good idea to document it somewhere.

**Comment by anilneeluri** [comment]
Thanks for the reply. It is Helpful.
