### ISSUE TITLE
How to set up a comparison function

### ISSUE THREAD

**Issue by Arvhus** [gunthercox/ChatterBot#932]
Hi I recently tried to incorporate my own comparison method into Chatterbot and received the following error

> 'function' object has no attribute 'get_initialization_functions'

From the documentation I understood that all that was required was handling the statements that would come into the function and returning a confidence value. Could you tell me where I'm going wrong? Why should there be a get_initialization_functions function?

**Comment by gunthercox** [comment]
Hi @Arvhus Take a look at the existing comparison functions:

https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/comparisons.py

Your comparison function should be on a class that inherits from `Comparator` which can be imported using:

```
from chatterbot.comparisons import Comparator
```

The reason this class is used is because sometime it is necessary for various setup processes to be run a single time when a chat bot first starts up and the `Comparator` class makes it easier to package all of these prerequisite steps together.

After you create the class, you'll want to put your comparison logic in a function called `compare` on your class. The `compare` method should return a number between 0 and 1 representing the percent of similarity between the two statements being compared.

Let me know if there is anything I can help with or clarify.

**Comment by Arvhus** [comment]
Thanks a lot @gunthercox ! Tried it out and it works perfectly :+1:
