### ISSUE TITLE
learning_feedback_example error: 'SQLStorageAdapter' object has no attribute 'create_conversation'

### ISSUE THREAD

**Issue by ken-talkingsource** [gunthercox/ChatterBot#958]
ChatterBot version : 0.7.6
python version : 3.6.2

In learning_feedback_example.py line 26 has an error :
```
CONVERSATION_ID = bot.storage.create_conversation()
'SQLStorageAdapter' object has no attribute 'create_conversation'
```
How should I fix that ?

---

Thanks @lesleslie 

Reinstall from git fix the problem.

`pip3 uninstall chatterbot`
`pip3 install git+git://github.com/gunthercox/ChatterBot.git@master`

**Comment by lesleslie** [comment]
on line 239 of chatterbot/storage/sql_storage.py do you see:

def create_conversation(self):


if not you need to clone/download/merge your ChatterBot source again from
github.  there have been 67 commits to the master since 0.76 was released.
 this is one of them i'm thinking.


Les Leslie
Principal / Developer
Wedgwood Web Works
les@wedgwoodwebworks.com
(406) 640-4222

**Comment by evgenibers** [comment]
Same issue. @ken-talkingsource Have you figured out what is wrong?

**Comment by ken-talkingsource** [comment]
Reinstall from git fix the problem.

```
pip3 uninstall chatterbot
pip3 install git+git://github.com/gunthercox/ChatterBot.git@master
```
