### ISSUE TITLE
Change unknown responses

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#984]
Today when the chatterbot got a untrained statement, the standard responds will be "The Current Time is XX:XX"

Where can I change that? 

Thanks

**Comment by vkosuri** [comment]
If any response not found chatterbot will pick a random response form existing statements, This phenomenon you could find in ``BestMatch`` adapter at line 25

https://github.com/gunthercox/ChatterBot/blob/b611cbd0629eb2aed9f840b50d1b3f8869c2589e/chatterbot/logic/best_match.py#L25

and also look into how random_respnse_selection works 
https://github.com/gunthercox/ChatterBot/blob/b611cbd0629eb2aed9f840b50d1b3f8869c2589e/chatterbot/response_selection.py#L55

**Comment by tisuchi** [comment]
@vkosuri 

I just trained up the bot, but it returns me `The current time is 08:17 AM` response although I have a statement record `How are you doing?`.

Any suggestion for that?

**Comment by vkosuri** [comment]
@tisuchi I am sorry i didn't understand your question, could you please elaborate?

**Comment by tisuchi** [comment]
@vkosuri 

I have a record in a statement table called `How are you doing?`. In response table, it has mapped properly also. However, when I send `How are you doing?` to chatterbot, it always response `The current time is -----`, that is not expected. 

I know, this return always come if there is no data. I have data, but why still it shows that not found response?

**Comment by ajwsert** [comment]
I also have been having this issue. No matter what's trained it keeps responding that way. I found out the "culprit" could be the TimeLogicAdapter, whenever it's used that issue happens. Apparently that adapter always provide a Statement then BestMatch seems to always pick it up. The workaround for now is to not use TimeLogicAdapter altogether :/

**Comment by vkosuri** [comment]
I think that would be nice workaround if that works for everyone.

**Comment by gunthercox** [comment]
I'm going to close this ticket off. It has been a while so please let me know if there is anything critical that I have overlooked. My thoughts on the subject are as follows:

1. If you want to change a past, or existing item that a chat bot has responded with please edit the data in your database.
2. I think the ability to allow promotion of "good" responses and demotion of "bad" responses is valuable. Because of this I will be looking into the possibility of supporting this functionality in the future. Please refer to #1152 for details.
