### ISSUE TITLE
Why using NLTK Naive Bayes Classifier used in Time logic adapter? 

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#994]
[NLTK Naive Bayes Classifier](http://www.nltk.org/_modules/nltk/classify/naivebayes.html) only return 1 or 0 as confidence and it always return 1 wrongly when user input several characters(e.g abc), 

https://github.com/gunthercox/ChatterBot/blob/a4a7b0287c3516975770d6f9ab1e5b8fa5572e1c/chatterbot/logic/time_adapter.py#L61

why don't you use compare_statements in best match adapter which return a proper confidence and more standardized. 

https://github.com/gunthercox/ChatterBot/blob/351971a21e603642f5797c33e924c4195f96682b/chatterbot/logic/best_match.py#L36

**Comment by gunthercox** [comment]
The Naive Bayes Classifier was chosen because it provides a fairly simple and efficient way to achieve text classification. Since the classification is feature based, it can determine what features are important based on the examples provided.

Text classification was chosen because it seemed like the best solution to solve the problem of determining if the input text was time-related. Text comparison might not work as well here because it would be less efficient, requiring each example statement to be compared for every text input.

**Comment by nggary** [comment]
thanks for the answer
