### ISSUE TITLE
Showing chatbot.train is callable for any of the scripts

### ISSUE THREAD

**Issue by riktimmondal** [gunthercox/ChatterBot#998]
![screenshot from 2017-09-26 15-46-50](https://user-images.githubusercontent.com/24415468/30855370-595d973a-a2d2-11e7-98cc-b8849946b5a2.png)

**Comment by vkosuri** [comment]
@riktimmondal You could resolve you in two ways.

1. i think you cloned chatterbot repository from GitHub, then you could try like this ``pip install -r dev-requirements.txt`` and ``pip install -r requirements``

2. The other could be you need specify chattebot as your source repository, I don't how do that in Visaul Studio Code.

**Comment by gunthercox** [comment]
@riktimmondal I don't think this is anything I can fix. The code linting tool in Visual Studio is having trouble detecting that the `train` method is callable because it is a property that returns a callable.

I'm going to close this ticket off because there isn't an actionable change that I'm aware of that I can do to fix this.
